# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "B&G Discount App"
client_id = "f157678dea357b26328c05a8f6b71a70"
application_url = "https://public-publish-res-page.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://public-publish-res-page.trycloudflare.com/auth/callback",
  "https://public-publish-res-page.trycloudflare.com/auth/shopify/callback",
  "https://public-publish-res-page.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "test-bloom-connect.myshopify.com"
