name = "Tag Discount"
type = "product_discounts"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/tags/:functionId/new"
details = "/tags/:functionId/:id"


[input.variables]
namespace = "$app:tags-discount"
key = "function-configuration"
