name = "Collection Discount"
type = "product_discounts"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/collection/:functionId/new"
details = "/collection/:functionId/:id"


[input.variables]
namespace = "$app:collection-discount"
key = "function-configuration"