name = "Free Gift"
type = "product_discounts"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/order/:functionId/new"
details = "/order/:functionId/:id"
